name: Conformances Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Load cached venv
        id: cached-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key:
            venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version
            }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "$VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

      - name: Create Proof Programs symlink
        run: make create-proof-programs-symlinks

      - name: Compile Cairo Zero programs
        run: make compile
